version: '3.5'

services:
  front-web:
    container_name: front-web
    build:
      context: .
      dockerfile: Dockerfile

    restart: always

    ports:
      - '5001:5000'

    environment:
      - NODE_ENV=production