
export const SET_ALL_HOSPITALS="SET_ALL_HOSPITALS";


export const ADD_IMAGE="ADD_IMAGE";
export const REMOVE_IMAGE="REMOVE IMAGE";
export const GET_ALL_IMAGES ="GET_ALL_IMAGES";
export const SET_HOSPITAL="SET_HOSPITAL";


export const MARK_VERIFIED="MARK_VERIFIED";
export const SET_VALIDATIONS="SET_VALIDATIONS";
export const SET_VALIDATION="SET_VALIDATION";
export const SET_VALIDATIONS_START="SET_VALIDATIONS_START";
export const SET_VALIDATIONS_STOP="SET_VALIDATIONS_STOP";

export const SET_ISSUES="SET_ISSUES";
export const SET_HISTORY="SET_HISTORY";

export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';




